# Generated by Django 4.0.4 on 2022-07-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_remove_ingredient_unit_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
    ]
