# Generated by Django 4.1 on 2022-08-31 04:01

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_comment_options_alter_recipe_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default_food.png', upload_to='recipe_pics', validators=[recipes.validators.validate_file_extension, recipes.validators.file_size]),
        ),
    ]
